# Kurz-Handbücher für Spiele und Software. Alle Spiel-Fakten wurden aus dem Spielcode ausgelesen.
# Spiele: quick = Schnellstart-Schritte, core = (Titel, Satz), pc/mobile = (Aktion, Taste/Geste),
#         tips = Profi-Tipps, facts = (Zahl, Beschriftung), table = (Überschrift, Spalten, Zeilen), save = Speichern

MANUALS = {
 "mandat": dict(
  intro="Kapitel 1 ist spielbar: 28 Tage Wahlkampf in Lindenbrück bis zur Kommunalwahl. Kreisstadt und Bundestag folgen.",
  quick=["„Neues Spiel“ wählen und deine Figur erstellen: Name, Geschlecht, Aussehen.",
         "Ein Herzensthema wählen, dann eine eigene Liste gründen oder in eine von 6 Parteien eintreten.",
         "Tag 1: Dorf erkunden, Leute ansprechen, an Haustüren klingeln.",
         "Die Zielleiste oben zeigt dir immer den nächsten Schritt."],
  core=[("28 Tage Wahlkampf", "Die Kommunalwahl ist an Tag 28. Jeder Tag hat 10 Energie, jede Aktion kostet welche."),
        ("Vier Säulen", "Bekanntheit, Vertrauen, Netzwerk und Organisation entscheiden die Wahl. Integrität und Skandalrisiko laufen mit."),
        ("Sechs Wählergruppen", "Landwirtschaft, Gewerbe, Familien, Senioren, Junge Leute, Pendler. Was die einen freut, kostet bei anderen Sympathie."),
        ("Echter Gemeindehaushalt", "Hebesätze, freiwillige Leistungen, Investitionen. Ein unbezahlbares Programm kostet Vertrauen."),
        ("Stammtisch-Duell", "Donnerstag bis Samstag im Krug: 3 Behauptungen, für jede 3 Fakten-Antworten zur Wahl."),
        ("Eigene Liste", "Bis Tag 20 brauchst du 30 Unterschriften. Mit 60 kannst du zusätzlich als Bürgermeister/in antreten.")],
  pc=[("Laufen", "Pfeiltasten"), ("Sprechen, Bestätigen", "Enter / Leertaste / Z"), ("Menü, Zurück", "Esc / X"), ("Karte", "M / K"), ("Tag beenden", "N"), ("Vollbild", "F")],
  mobile=[("Laufen", "Steuerkreuz links oder auf die Karte tippen"), ("Bestätigen", "A-Knopf rechts"), ("Menü, Karte, Tag beenden", "Knöpfe oben rechts"), ("Ausrichtung", "Querformat")],
  tips=["Die Kaffeemaschine im Büro bringt jeden Tag +1 Energie, die Plakatwand +15 % Bekanntheit. Dein Büro ist das Hinterzimmer im Krug (45 € Miete).",
        "Samstag ist Markttag: Der Infostand bringt Bekanntheit und Unterschriften.",
        "Dienstags tagt der Rat. Eine Frage in der Einwohnerfragestunde fällt positiv auf.",
        "Plakatieren ist ab Tag 8 erlaubt, vorher brauchst du die Genehmigung im Bürgerbüro.",
        "Der letzte Bus fährt um 19:12 Uhr, sonntags fährt keiner."],
  facts=[("28", "Tage Wahlkampf"), ("7", "Parteien"), ("16", "Ratssitze"), ("2.600", "Einwohner in Lindenbrück")],
  save="Automatisch jeden Abend beim Schlafengehen, zusätzlich im Menü unter System. Der Spielstand liegt nur in deinem Browser auf diesem Gerät."),

 "sternenwurf": dict(
  intro="Drehen, sammeln, verschmelzen: Am Altar der Sterne bekommst du Ausrüstung. Je seltener, desto mächtiger.",
  quick=["„Neues Spiel“ wählen. Ein Leitfaden mit 14 Aufgaben und einem Pfeil führt dich, jede Aufgabe bringt Gold.",
         "Im Wald Holz hacken, dann mit dem Gold am Altar der Sterne in der Mitte drehen.",
         "Im Menü unter Ausrüstung „Bestes anlegen“ wählen und bei Baumeisterin Hilde einen Holzfäller anheuern.",
         "Mit R den Auto-Roll einschalten und im Prüfungsturm im Norden Etage 1 bezwingen."],
  core=[("Der Altar", "Jeder Dreh kostet Gold und bringt ein Ausrüstungsteil. Ein Teil mit „1 : N“ fällt mit der Chance Glück geteilt durch N."),
        ("Verschmelzen", "4 gleiche Teile ergeben 1 Teil mit Stern, bis ★4. Aus Gearscore 11 wird so 77."),
        ("Prüfungsturm", "30 Etagen. Du brauchst genug Gearscore und Schaden pro Sekunde, Elementschwächen geben ×1,5."),
        ("5 Welten", "Jede neue Welt bringt mehr Glück, höhere Drehkosten und eigene Teile und Pets."),
        ("50 Pets", "Eier im Sternengarten ausbrüten. Bis zu 3 Begleiter geben Gold, Glück oder Macht."),
        ("Basis und Skills", "Holzfäller, Bergleute und Gebäude bringen Gold pro Sekunde. Der Skillbaum hat 3 Zweige.")],
  pc=[("Laufen", "Pfeiltasten / Klick"), ("Ansprechen", "Enter / Leertaste / Klick"), ("Menü", "Esc / Rechtsklick"), ("Auto-Drehen an/aus", "R"), ("Auto-Brüten an/aus", "T"), ("Animation überspringen", "Enter / Klick")],
  mobile=[("Laufen, Ansprechen", "Tippen"), ("Auto-Drehen", "Auf „Auto-Roll“ im HUD tippen"), ("Questtafel", "Auf das Auftragsfeld tippen"), ("Vollbild", "Knopf ⛶ unten links, Querformat")],
  tips=["Jedes neue Teil im Kodex gibt dauerhaft +1 % Glück, eine komplette Welt +10 %. Jedes neue Pet +1 % Gold und Glück.",
        "Auto-Verkauf mit Bedacht: Verkaufte Teile kannst du nicht mehr verschmelzen.",
        "Der Skill „Sternensegen“ (5 Punkte) gibt dauerhaft Glück ×1,5.",
        "Pity-Garantie: Spätestens nach 1.000 Drehs ohne Episch ist der nächste episch.",
        "Die Dreh-Animation ist nur Show. Überspringen ändert nichts an deinen Chancen."],
  facts=[("120", "Ausrüstungsteile"), ("50", "Pets"), ("30", "Turm-Etagen"), ("1 : 10 Mio.", "Krone des Alls")],
  table=("Die fünf Welten", ["Welt", "Glück", "Drehkosten", "Freischaltung"],
         [["Sternenfall-Tal", "×1", "×1", "Start"], ["Mondhain", "×2", "×6", "Etage 3 + 5.000 G"], ["Sternenwarte", "×4", "×30", "Etage 6 + 150.000 G"],
          ["Glutkrater", "×9", "×150", "Etage 12 + 8 Mio. G"], ["Kosmos-Riss", "×20", "×800", "Etage 18 + 600 Mio. G"]]),
  save="Automatisch beim Kartenwechsel, zusätzlich im Menü unter Speichern. Der Spielstand liegt nur in deinem Browser auf diesem Gerät."),

 "idle-legenden": dict(
  intro="Gold vertreibt den Grauen Schleier. Je reicher Goldhafen wird, desto heller wird die Welt.",
  quick=["„Neues Spiel“ wählen. Ratgeberin Elara erklärt dir das Ziel.",
         "Im Westen am Erzfelsen die Aktionstaste drücken und Gold schlagen.",
         "Bei Bruno den ersten Minenarbeiter anheuern (15 G). Ab jetzt verdienst du Gold pro Sekunde.",
         "Dem Auftragsfenster oben links folgen. Hilfe gibt es im Menü unter „Ratgeber“."],
  core=[("Passives Einkommen", "Arbeiter +1 G/s, Farm +10, Golem +100, Bankier +1.000. Jede Minentiefe gibt Arbeitern und Golems ×1,5."),
        ("Aufträge", "33 feste Aufträge, danach endlose Ziele mit Belohnung."),
        ("Stadtstufen", "Ab 100 Tsd., 10 Mio., 1 Mrd. und 1 Bio. G steigt Goldhafen auf. Jede Stufe gibt dauerhaft +25 % Einkommen."),
        ("Kämpfe", "Vier Portale bis zum Boss. Einzelkampf, Serie von 5 oder Auto-Grind im Hintergrund."),
        ("Beute", "Vier Seltenheiten von Gewöhnlich bis Legendär. Lootkisten öffnest du im Menü oder bei Kalle, bis zu 50 auf einmal."),
        ("Goldene Wiedergeburt", "Ab 1 Mrd. G beim Orakel neu starten und Seelentaler kassieren. Jeder gibt +10 % für immer.")],
  pc=[("Laufen", "Pfeiltasten / Klick"), ("Aktion, Ansprechen", "Enter / Leertaste / Klick"), ("Menü", "Esc / Rechtsklick")],
  mobile=[("Laufen, Aktion", "Tippen"), ("Vollbild", "Knopf ⛶ unten links"), ("Ausrichtung", "Querformat")],
  tips=["Fang den Goldfuchs auf dem Marktplatz. Er kommt etwa alle 3 Minuten und bringt Goldrausch, einen Schatz oder Lootkisten.",
        "In der Mine lohnen die Adern: Gold ×2, Kristall ×5 ab Tiefe 3, Mithril ×15 ab Tiefe 6.",
        "Die Beutekisten auf dem Markt füllen sich jede Minute neu. Vorsicht, manche sind Mimiks.",
        "Das Goldkönig-Set (5 Teile) verdoppelt komplett alle Werte und dein Einkommen.",
        "Vor dem Schließen speichern: Dann gibt es beim nächsten Start bis zu 8 Stunden Offline-Ertrag."],
  facts=[("33", "Aufträge"), ("4", "Portale"), ("5", "Stadtstufen"), ("8 Std.", "Offline-Ertrag")],
  save="Beim Chronisten Elias oder im Menü, außerdem automatisch beim Kartenwechsel. Offline verdienst du 50 % deines Einkommens, höchstens 8 Stunden, gutgeschrieben beim nächsten „Fortsetzen“."),

 "wrestling-tcg": dict(
  intro="Packs aufreißen, das Album füllen, im Ring punkten. Fair und ohne echtes Geld.",
  quick=["Spiel öffnen und das Willkommens-Pack aufreißen, mit garantiert mindestens einer seltenen Karte. Du startest mit 300 W$.",
         "Jeden Tag die Anmeldeserie abholen und die 2 Gratis-Rookie-Packs öffnen.",
         "Neue Karten im Album ansehen, Duplikate verkaufen.",
         "Im Tab „Quests“ Belohnungen einsammeln."],
  core=[("Packs", "Rookie (gratis), Championship Gold, Royal Rumble mit 30 Karten und Pay-per-View. Bezahlt wird mit W$."),
        ("Album", "250 Karten im Hauptset, dazu Season-, Pay-per-View-Karten und 8 Titelgürtel."),
        ("Ring", "5 Plätze zum Wochenthema. Der Show-Wert zählt, der Champion doppelt. Bis zu 1.000 W$ pro Woche."),
        ("Grading", "Karte einreichen und eine Note von 1 bis 10 bekommen. Eine Gem Mint 10 ist 8× so viel wert."),
        ("Quests", "Täglich 3 Aufgaben mit 100 bis 200 W$, alle drei geschafft: +150 W$ Bonus. Dazu 21 Erfolge."),
        ("Codes", "Codes aus der Community bringen W$ oder Pack-Gutscheine.")],
  pc=[("Pack aufreißen", "Über den Rand wischen / Enter"), ("Karte aufdecken", "Klick / Enter / Leertaste"), ("Einmarsch starten", "Karte im Album gedrückt halten"), ("Dialog schließen", "Esc")],
  mobile=[("Pack aufreißen", "Über den Rand wischen"), ("Karte aufdecken", "Tippen"), ("Holo-Glanz", "Handy neigen (abschaltbar)"), ("Ausrichtung", "Hochformat")],
  tips=["Die „Karte des Tages“ kommt an diesem Tag in jedem Pack doppelt so oft.",
        "Pity-Schutz: Spätestens jedes 12. Rookie-Pack hat Ultra Rare oder besser, das 100. Gold-Pack garantiert eine Secret Mythic.",
        "„Duplikate verkaufen“ behält immer dein bestes Exemplar und rührt gegradete Karten nicht an.",
        "Im Ring auf den Champion-Platz die Karte mit dem höchsten Show-Wert zum Wochenthema setzen.",
        "Spielstand sichern: Über Export bekommst du einen Text-Code, mit dem du ihn auf ein anderes Gerät mitnimmst."],
  facts=[("250", "Karten im Hauptset"), ("6", "Seltenheiten"), ("2", "Gratis-Packs pro Tag"), ("3", "Hall-of-Fame-Karten")],
  table=("Packs im Überblick", ["Pack", "Preis", "Karten", "Ultra Rare+"],
         [["Rookie", "gratis", "5", "ca. 19 %"], ["Championship Gold", "600 W$", "5", "ca. 77 %"], ["Pay-per-View", "1.000 W$", "5", "ca. 35 %"], ["Royal Rumble", "2.500 W$", "30", "ca. 97 %"]]),
  save="Automatisch in deinem Browser, mit Sicherungskopie. Über Export und Import nimmst du deinen Spielstand als Text-Code mit."),

 "kritzelheld": dict(
  intro="Für Kinder ab dem Vorschulalter (Empfehlung). Kein Internet, keine Werbung, keine Daten, die das Gerät verlassen.",
  quick=["Auf dem Startbildschirm ein Profil antippen oder mit „+ Neu“ anlegen (bis zu 6 Profile).",
         "„Spielen!“ öffnet die Spielwelt, „Schreiben“ führt zur Schatzkarte.",
         "Ein Zeichen antippen: Eule Kritzel macht es vor.",
         "Mit dem Finger nachfahren. Ab 1 Stern ist das nächste Zeichen frei."],
  core=[("96 Zeichen", "Großbuchstaben, Kleinbuchstaben, Ziffern und Zahlen bis 99, jeweils mit 1 bis 3 Sternen."),
        ("Faire Prüfung", "Jeder Strich muss nachgefahren werden. Wildes Ausmalen zählt nicht."),
        ("Federn", "Bis zu 25 Federn pro Zeichen, dazu Federn aus Minispielen, Erfolgen und dem täglichen Geschenk."),
        ("Eulen-Shop", "78 Teile in 8 Rubriken, von Hut bis Umhang, 6 davon legendär."),
        ("Baumhaus", "Für 500 Federn freischalten und innen wie außen einrichten."),
        ("14 Minispiele", "Lernspiele wie Silben klatschen und Buchstaben-Angeln, dazu Spaß von Torschuss bis Vier gewinnt.")],
  pc=[("Nachfahren", "Maus gedrückt halten"), ("Radieren", "Knopf ⌫"), ("Nochmal vormachen", "Knopf ★"), ("Zurück", "Knopf ‹")],
  mobile=[("Nachfahren", "Finger oder Stift"), ("Radieren", "Knopf ⌫"), ("Nochmal vormachen", "Knopf ★"), ("Zurück", "Knopf ‹ / Zurück-Taste")],
  tips=["Elternbereich: das Zahnrad auf dem Startbildschirm 1,5 Sekunden gedrückt halten.",
        "Die nötige Abdeckung (Standard 75 %) lässt sich von 50 bis 95 % einstellen, dazu Strenge und Stiftdicke.",
        "Im Elternbereich siehst du pro Kind Sterne, Federn, Erfolge und gemalte Bilder.",
        "„Vormachen automatisch“ abschalten, wenn das Kind ein Zeichen schon sicher kann.",
        "„Profil zurücksetzen“ startet bei null. Das ist praktisch für Geschwister."],
  facts=[("96", "Zeichen"), ("14", "Minispiele"), ("32", "Erfolge"), ("0", "Werbung")],
  save="Alles bleibt auf dem Gerät. Die App braucht kein Internet und sendet keine Daten."),

 "kasse-oder-zettel": dict(
  intro="Jedes Level spielst du zweimal mit exakt denselben Gästen: erst mit Zettel und Stift, dann mit Kasse. Danach kommt der direkte Vergleich.",
  quick=["„Jetzt spielen“ wählen und ein Level aussuchen, oder „Schnellstart“ für Level 1.",
         "„Los geht's!“ drücken. Nach dem Countdown beginnt die Schicht.",
         "Runde 1 mit Zettel, Runde 2 automatisch mit Kasse.",
         "Am Ende siehst du Umsatz, Trinkgeld und Sterne beider Runden im Vergleich."],
  core=[("Zettel-Runde", "Bestellung notieren, Zettel getrennt zu Küche und Tresen bringen, Rechnung am Tresen ausrechnen, Wechselgeld zählen."),
        ("Was schiefgeht", "Unleserliche Zettel, falsche Pizza, verzähltes Wechselgeld. Gutscheine und getrennte Rechnungen kosten Zeit."),
        ("Kassen-Runde", "Der Bon geht sofort an Küche und Tresen, bezahlt wird per Karte direkt am Tisch."),
        ("QR-Bestellung", "Ab Level 3 bestellen manche Gäste selbst per QR-Code."),
        ("Geduld", "Läuft die Geduld ab, gehen Gäste oder geben kein Trinkgeld."),
        ("Sterne", "Umsatz plus Trinkgeld ergibt bis zu 3 Sterne pro Runde, 48 insgesamt.")],
  pc=[("Tisch bedienen", "Klick / Tasten 1–8"), ("Küche", "K"), ("Tresen", "T"), ("Pause", "Esc / P"), ("Vollbild", "F")],
  mobile=[("Tisch, Küche, Tresen", "Antippen"), ("Ziele vormerken", "Bis zu 4 nacheinander antippen"), ("Pause", "Knopf oben rechts"), ("Ausrichtung", "Querformat")],
  tips=["Folge dem orangen Ring. Er zeigt dir das nächste sinnvolle Ziel.",
        "Jede zahlende Gruppe in Folge hebt das Trinkgeld um 10 %, bis ×2,0. Fehler setzen die Serie zurück.",
        "Schnelle Bedienung bringt 4 bis 18 % Trinkgeld.",
        "Stammgäste zahlen doppelt, also bevorzugt bedienen.",
        "Der Kellner trägt bis zu 5 Teller und Gläser. Wege zu Küche und Tresen bündeln."],
  facts=[("8", "Level"), ("48", "Sterne"), ("2", "Runden pro Level"), ("120 s", "Silvester-Schicht")],
  table=("Die 8 Level", ["Level", "Tische", "Zeit"],
         [["1 · Mittagstisch", "3", "75 s"], ["2 · Kaffee & Kuchen", "4", "80 s"], ["3 · Feierabend", "5", "85 s"], ["4 · Freitagabend", "6", "90 s"],
          ["5 · Stammtisch", "6", "90 s"], ["6 · Geburtstagsfeier", "7", "100 s"], ["7 · Samstag – volle Hütte", "8", "105 s"], ["8 · Silvester", "8", "120 s"]]),
  save="Bestwerte und Sterne speichert das Spiel automatisch in deinem Browser. Ein Level wird frei, sobald das vorige in beiden Modi gespielt ist."),
}

# ---------------------------------------------------------------- Software-Seiten
SOFTWARE_PAGES = {
 "diktakte": dict(
  claim="Diktieren. Ablegen. Erledigt.", sub="Diktierprogramm für Anwältinnen und Anwälte: juristische Schreibweise, Aktenverwaltung, Fristen und E-Mail-Versand in einem Programm. Die Spracherkennung läuft komplett auf dem eigenen PC.",
  status="Hobbyprojekt · Version 0.7", cta="feedback",
  meta="Diktakte: Diktierprogramm für Anwälte mit lokaler Spracherkennung, juristischer Schreibweise, Aktenverwaltung, Fristenberechnung und beA-Versand.",
  why=[("Diktate bleiben im Haus", "Die Spracherkennung (Whisper) läuft lokal. Kein Diktat geht ins Internet."),
       ("Schreibt wie ein Jurist", "Aus „Paragraph achthundertdreiundzwanzig Absatz eins BGB“ wird automatisch „§ 823 Abs. 1 BGB“."),
       ("Ohne PC-Kenntnisse", "Große Knöpfe, F9 für das Mikrofon, alles wird automatisch gespeichert.")],
  steps=[("Akte wählen", "Akte links anklicken oder neu anlegen. Diktakte prüft dabei automatisch auf Interessenkollision."),
         ("F9 drücken und sprechen", "Rot = hört zu, gelb = schreibt. Funktioniert auch mit Fußschalter oder Diktiermikrofon."),
         ("Brief erstellen", "„An Gegenseite“, „An Gericht“ oder „An Mandanten“: der Text landet im eigenen Briefkopf."),
         ("Versenden", "Per E-Mail als PDF, über beA als PDF/A oder als Word-Datei. Die Kopie liegt automatisch in der Akte.")],
  feats=[("mic", "Lokale Spracherkennung", "Whisper, ohne Cloud", "Das Sprachmodell (ca. 550 MB) wird einmalig geladen, danach bleibt alles auf dem PC. Mit Grafikkarte schnell, ohne Grafikkarte 2 bis 7 Sekunden pro Satz."),
         ("file", "Juristische Schreibweise", "§§, Rn., Aktenzeichen automatisch", "„drei O hundertdreiundzwanzig Strich vierundzwanzig“ wird „3 O 123/24“, „fortfolgende“ wird „ff.“. Zwischen § und Zahl steht immer ein geschütztes Leerzeichen."),
         ("eye", "Lernt dazu", "Unsichere Wörter prüfen", "Nach dem Diktat meldet Diktakte wenige unsichere Wörter. „Stimmt so“ oder „Korrigieren“, und beim nächsten Mal sitzt es."),
         ("clock", "Fristen", "Nach §§ 187, 188 BGB und § 222 ZPO", "Häufige Fristen anklicken, das Ende wird berechnet, Wochenenden und Feiertage des Bundeslands verschieben automatisch. Vorfrist eine Woche vorher, Fristenliste zum Ausdrucken."),
         ("folder", "Akten & Volltextsuche", "Auch in Briefen, E-Mails und Scans", "Ab drei Buchstaben durchsucht Diktakte alle Akten samt Inhalt. Eingescannte Post wird mit der Windows-Texterkennung lesbar gemacht."),
         ("users", "Kollisionsprüfung", "Nach § 43a Abs. 4 BRAO", "Beim Anlegen einer Akte prüft Diktakte, ob der Mandant anderswo Gegner war. Tippfehler und Schreibvarianten werden ausgeglichen."),
         ("print", "RVG & Rechnungen", "Mit E-Rechnung (XRechnung)", "Gebühren nach § 13 RVG berechnen, Rechnung als Brief und PDF erstellen, dazu eine XRechnung. Offene Posten auf einen Blick."),
         ("win", "Mehrplatz & Sicherung", "Anwalt und Sekretariat", "Gemeinsamer Datenordner auf dem NAS, tägliche Datensicherung auf USB-Festplatte oder NAS, die letzten 30 Stände bleiben erhalten.")],
  gallery=[("frist.png", "Neue Frist: Ende wird automatisch berechnet"), ("fristenliste.png", "Fristenliste zum Ausdrucken"), ("unsicher-leiste.png", "Unsichere Wörter prüfen, Diktakte lernt dazu"), ("dokumente.png", "Alle Dokumente der Akte"), ("email.png", "Brief direkt als E-Mail versenden")],
  manual=[("Welche Sprachbefehle gibt es?", "Allein gesprochen: „Brief an Gegenseite“, „Brief an Gericht“, „E-Mail senden“, „Frist eintragen“, „Als PDF speichern“, „Baustein …“, „Lösch das“, „Mikrofon aus“. Im Text: „neuer Absatz“, „Klammer auf“, „Doppelpunkt“ und mehr."),
          ("Was brauche ich?", "Windows 10 (ab Version 2004) oder Windows 11, 64 Bit, und ein Mikrofon. LibreOffice oder OpenOffice für die Briefe, das Setup bietet die Installation an. .NET muss nicht installiert sein."),
          ("Wo liegen meine Daten?", "Alles liegt lokal unter C:\\Kanzlei: Akten, Vorlagen und Einstellungen. Bei Updates bleiben die Akten erhalten."),
          ("Ersetzt Diktakte die Fristenkontrolle?", "Nein. Die Berechnung ersetzt nicht die eigene Prüfung jeder Frist. Deshalb gibt es die Fristenliste zum Ausdrucken mit Kontroll-Spalte."),
          ("Kann ich Diktakte bekommen?", "Diktakte ist ein privates Hobbyprojekt und derzeit nicht öffentlich verfügbar. Feedback und Ideen sind trotzdem willkommen.")]),
 "deskboard": dict(
  claim="Dein Desktop. Endlich aufgeräumt.", sub="Eine eigene Startoberfläche für Windows: Kacheln für Programme und Webseiten, Reiter für Privat und Arbeit, Widgets und ein Notizblock zum Abreißen. Kostenlos für alle.",
  status="Kostenlos · Version 1.7", cta="download",
  meta="DeskBoard: kostenlose Desktop-Oberfläche für Windows mit Programm- und Webseiten-Kacheln, Widgets, Reitern und Notizblock. Jetzt gratis herunterladen.",
  why=[("Alles auf einen Blick", "Programme, Webseiten und Ordner als große Kacheln statt Icon-Chaos."),
       ("Nur was du willst", "Jedes Widget lässt sich hinzufügen und wieder entfernen."),
       ("Kostenlos", "Ohne Abo, ohne Werbung, dauerhaft gratis.")],
  steps=[("Herunterladen", "Die Setup-Datei für Windows laden."),
         ("Installieren", "Setup starten. Keine Admin-Rechte nötig."),
         ("Einrichten", "Rechtsklick auf die Fläche: Programme, Webseiten und Widgets hinzufügen.")],
  feats=[("grid", "Kacheln", "Programme, Webseiten, Ordner", "Programme per Rechtsklick oder per Drag & Drop aus dem Explorer. Webseiten holen sich Titel und Icon selbst und öffnen auf Wunsch ohne Browser-Rahmen."),
         ("widget", "Widgets", "Wetter, Kalender, Musik und mehr", "Wetter, Kalender, offene Programme, Musiksteuerung, Zwischenablage, Countdown, Weltzeituhr, Uhr und Systemauslastung."),
         ("note", "Notizblock", "Zum Abreißen", "Seite an der Perforation greifen und wegziehen: auf die Fläche wird sie zur Sticky Note, auf den Papierkorb ist sie weg."),
         ("toggle", "Reiter & Favoriten", "Privat und Arbeit getrennt", "Reiter trennen die Arbeitsfläche. Die Favoritenleiste schlägt die Programme vor, die du am häufigsten startest."),
         ("brand", "Design", "Hintergrund, Kachelstil, Farben", "Farbe, Verlauf, Bild oder sogar Video als Hintergrund, dazu Kachelstil, Akzentfarbe und Raster. Für Bastler: eigene user.css."),
         ("clock", "Tastenkürzel", "Schnell überall", "Einfach lostippen zum Suchen, Strg+Alt+N für eine Schnellnotiz von überall, Strg+Alt+Leertaste holt DeskBoard zurück."),
         ("book", "Eingebaute Anleitung", "Hilfe mit F1", "Der Knopf „Hilfe“ oder F1 erklärt alles, was die Oberfläche kann."),
         ("win", "Autostart", "Startet mit Windows", "Ein Schalter unter „Design“, und DeskBoard ist nach dem Anmelden sofort da."),
         ("users", "Tickets & Kunden", "Kleine Auftragsverwaltung", "Tickets als Board mit Offen, Wartet, Abrechnung und Erledigt, dazu Kundenkartei mit Notizen und Dateien, Zeiterfassung per Timer und Rechnungen.")],
  gallery=[("tickets.png", "Tickets als Board: Offen, Wartet, Abrechnung, Erledigt"), ("kunden.png", "Kundenkartei mit Notizen, Dateien und Tickets"), ("widgets.png", "Widgets: Wetter, Kalender, Musik, Weltzeit, Zwischenablage"), ("favoriten.png", "Favoritenleiste mit den meistgenutzten Programmen"), ("anleitung.png", "Eingebaute Anleitung, jederzeit mit F1")],
  manual=[("Systemvoraussetzungen", "Windows 10 oder 11, 64 Bit."),
          ("Windows zeigt eine Warnung?", "Bei neuen Programmen kleiner Entwickler meldet Windows SmartScreen oft „Der Computer wurde durch Windows geschützt“. Klicke auf „Weitere Informationen“ und dann auf „Trotzdem ausführen“."),
          ("Wie komme ich zurück zu Windows?", "Gelber Knopf „Zum Desktop“. Zurück holst du DeskBoard mit Strg+Alt+Leertaste oder über das Symbol in der Taskleiste."),
          ("Wo werden meine Einstellungen gespeichert?", "Lokal auf deinem PC unter %APPDATA%\\DeskBoard, mit automatischer Sicherungskopie."),
          ("Wünsche?", "Sag uns unten im Feedback, welches Widget als Nächstes kommen soll.")]),
 "speisekarte": dict(
  claim="Die Karte, die nach dir aussieht.", sub="Speise-, Getränke-, Tages-, Menü- und Aktionskarten selbst gestalten und drucken. Mit eigenem Logo, Allergenen und QR-Code, in Minuten.",
  status="Hobbyprojekt · in Entwicklung", cta="feedback",
  meta="Speisekarten-Konfigurator: Speisekarte, Tageskarte, Menü- und Aktionskarte selbst gestalten. 9 Vorlagen, Allergene, Logo-Werkstatt, QR-Code, Druck als PDF.",
  why=[("Schnell", "Der Assistent führt Schritt für Schritt zur fertigen Karte."),
       ("Einheitlich", "Logo, Farben und Schriften passen auf jeder Karte zusammen."),
       ("Ohne Grafiker", "Vorlage wählen, Gerichte eintragen, drucken.")],
  steps=[("Assistent starten", "Kartenart und Vorlage wählen."),
         ("Inhalte eintragen", "Gerichte, Preise, Beschreibungen und Allergene."),
         ("Logo & QR-Code", "Logo einbauen, auf Wunsch einen QR-Code für Reservierung oder WLAN."),
         ("Drucken", "Den Kartenbeleg prüfen, dann drucken oder als PDF speichern.")],
  feats=[("file", "6 Kartenarten", "Von der Speisekarte bis zum Reserviert-Schild", "Speisekarte mit Deckblatt und Rückseite, Getränkekarte, Tageskarte, Menükarte, Aktionskarte und Reserviert-Schilder."),
         ("grid", "9 Vorlagen", "Vom Landgasthof bis Street Food", "Landgasthof, Hafenkontor, Trattoria, Kreidetafel, Fine Dining, Street Food, Bistro, Café und Kassenbon, jeweils mit passenden Farben und Schriften."),
         ("eye", "Allergene & Kennzeichnung", "Mit Legende auf der Karte", "Allergene pro Gericht anklicken, dazu Kennzeichen wie vegan, vegetarisch oder scharf. Die Legende erscheint automatisch."),
         ("brand", "Logo-Werkstatt", "Hintergrund entfernen inklusive", "Logo hochladen, Hintergrund entfernen, zuschneiden, einfärben oder einen Schriftzug erstellen."),
         ("print", "QR-Code", "Für Reservierung, Website oder WLAN", "Gäste scannen den Code mit der Handykamera. Er passt auf alle Kartenarten."),
         ("note", "Kartenbeleg", "Prüft deine Karte vor dem Druck", "Ein Beleg am Rand zeigt, ob alles passt, und gibt Tipps, etwa zu Kontrast oder QR-Code-Größe."),
         ("toggle", "Einfach oder Profi", "So viel Kontrolle, wie du willst", "Im einfachen Modus sind nur die wichtigsten Einstellungen sichtbar. Im Profi-Modus gibt es Zierelemente, Hervorhebungen und Feintuning."),
         ("clock", "Direkt bearbeiten", "Text auf der Karte anklicken und ändern", "Statt im Formular kannst du Texte auch direkt auf der Vorschau bearbeiten.")],
  manual=[("Welche Formate gibt es?", "DIN A4 als Standard, außerdem DIN A3 und DIN A5. Reserviert-Schilder lassen sich falten oder zu viert auf ein Blatt drucken."),
          ("Wie bekomme ich eine PDF-Datei?", "Unter „Drucken“ als Ziel „Als PDF speichern“ wählen und Hintergrundgrafiken einschalten."),
          ("Kann ich den Konfigurator nutzen?", "Der Konfigurator ist ein privates Hobbyprojekt in Entwicklung und derzeit nicht öffentlich verfügbar. Feedback und Ideen sind willkommen.")]),
}
